DROP table IF EXISTS E CASCADE

CREATE TABLE E AS SELECT i AS i,j AS j, 1 AS p, v AS v FROM webgoogle

DROP table IF EXISTS R1 CASCADE

CREATE TABLE R1 AS SELECT 1 AS d, i AS i, j AS j, sum(p) AS p, max(v) AS v FROM E GROUP BY d,i,j

DROP table IF EXISTS R2 CASCADE

CREATE TABLE R2 AS SELECT  2 AS d, R1.i AS i, E.j AS j, sum(R1.p*E.p) AS p, max(R1.v*E.v) AS v FROM R1 JOIN E ON R1.j=E.i WHERE R1.i!=R1.j GROUP BY R1.d,R1.i,E.j

